#!/bin/sh
# Thanks Nik Spyrtos! https://github.com/nikspyratos/toybox/blob/main/.hooks/pre-commit

# Save list of staged files (those intended for commit)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)

npm run format

# Re-add only the files that were originally staged
if [ -n "$STAGED_FILES" ]; then
  echo "$STAGED_FILES" | xargs git add
fi
